In [3]:
import numpy as np
from scipy.sparse import csr_matrix

In [7]:
# since defined the array of mXn where it forms the dense matrix which stroe all the zero and non-zero element 
# using the sparse matrix which store only the non-zero element values
#convert the dense to sparse
dense_matrix = np.array([[0, 0, 3], [0, 5, 0], [0, 0, 0]])
print(dense_matrix)

[[0 0 3]
 [0 5 0]
 [0 0 0]]


In [48]:
sparse_matrix=csr_matrix(dense_matrix)
print(sparse_matrix,end="----  ") #go with the rowwise
cscMatrix=csc_matrix(sparse_matrix)
print(cscMatrix) # go with the column wise

  (0, 2)	3
  (1, 1)	5----    (1, 1)	5
  (0, 2)	3


In [34]:
# Storage Efficiency and Memory Usage

from scipy.sparse import csr_matrix,csc_matrix,coo_matrix

def matrix_convert (martix):
    csrMatrix=csr_matrix(martix)
    cscMatrix=csc_matrix(martix)
    cooMatrix=coo_matrix(martix)
    return csrMatrix

#let make 10X10 matrix
matrix = np.random.choice([0, 0, 0, 0, 0, 1, 2, 3, 4, 5], size=(10, 10))
print(matrix_convert(matrix))

  (0, 1)	3
  (0, 8)	2
  (1, 2)	4
  (1, 3)	5
  (1, 4)	1
  (1, 5)	5
  (1, 7)	3
  (1, 8)	3
  (2, 0)	1
  (2, 1)	2
  (2, 3)	5
  (2, 5)	5
  (2, 7)	3
  (2, 9)	4
  (3, 0)	1
  (3, 1)	2
  (3, 2)	5
  (3, 3)	2
  (3, 4)	5
  (3, 7)	4
  (3, 8)	3
  (3, 9)	5
  (4, 0)	2
  (4, 1)	4
  (4, 5)	3
  :	:
  (5, 5)	1
  (5, 6)	5
  (5, 7)	5
  (5, 8)	1
  (6, 1)	5
  (6, 2)	1
  (6, 3)	1
  (6, 6)	3
  (6, 9)	2
  (7, 1)	1
  (7, 4)	2
  (7, 5)	3
  (7, 8)	5
  (8, 1)	3
  (8, 3)	5
  (8, 4)	2
  (8, 5)	5
  (8, 7)	5
  (8, 9)	2
  (9, 0)	4
  (9, 3)	5
  (9, 4)	5
  (9, 7)	1
  (9, 8)	4
  (9, 9)	3


In [25]:
 # np.random.seed(42)  # For reproducibility